vich_uploader:
    db_driver: orm

    mappings:
       article_img:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       categorie_img:
           uri_prefix: /images/categorie
           upload_destination: '%kernel.project_dir%/public/images/categorie'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       delivery_img:
           uri_prefix: /images/delivery
           upload_destination: '%kernel.project_dir%/public/images/delivery'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
     
